<?php
/** @var WebChemistry\Stripe\Bridge\Latte\Bar\StripeBar $this */
use WebChemistry\Stripe\Bridge\Latte\Bar\WebhookDebugInfo;
?>
<h1>Webhooks</h1>

<table class="tracy-sortable">
	<thead>
	<tr>
		<th>Class</th>
		<th>Events</th>
	</tr>
	</thead>
	<tbody>
	<?php foreach ($this->webhookProcessor->getWebhooks() as $webhook): $events = $webhook->getSubscribedEvents() ?>
		<tr>
			<td>
				<?= $webhook::class ?>
				<?php if ($webhook instanceof WebhookDebugInfo): ?>
					<br>
					<span style="font-size: .7rem;color:#888888"><?= $webhook->getDebugDescription() ?></span>
				<?php endif; ?>
			</td>
			<td><?= $events === null ? 'ALL' : implode('<br>', $events) ?></td>
		</tr>
	<?php endforeach; ?>
	</tbody>
</table>
